name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syyu --noconfirm
          pacman -S sudo archiso mkinitcpio-archiso git squashfs-tools grub --needed --noconfirm
          echo "ALL ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/nopasswd

      - name: Clone & Build
        run: |
          git clone https://github.com/cachyos/cachyos-live-iso.git cachyos-archiso
          cd cachyos-archiso
          ./buildiso.sh -p desktop -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: cachyos-archiso/out/**
