name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: CachyOS Setup
        run: |
          pacman-key --init
          pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key F3B607488DB35A47
          pacman -U --noconfirm \
            'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-20240331-1-any.pkg.tar.zst' \
            'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-22-1-any.pkg.tar.zst' \
            'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-22-1-any.pkg.tar.zst' \
            'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-7.0.0.r7.g1f38429-1-x86_64.pkg.tar.zst'
          sed -i '/^\[core\]/i \
          [cachyos-v3]\n\
          Include = /etc/pacman.d/cachyos-v3-mirrorlist\n\
          \n\
          [cachyos-core-v3]\n\
          Include = /etc/pacman.d/cachyos-v3-mirrorlist\n\
          \n\
          [cachyos-extra-v3]\n\
          Include = /etc/pacman.d/cachyos-v3-mirrorlist\n\
          \n\
          [cachyos]\n\
          Include = /etc/pacman.d/cachyos-mirrorlist\n\
          ' /etc/pacman.conf

      - name: Install dependencies
        run: |
          pacman-key --populate archlinux cachyos
          pacman -Syyu --noconfirm
          pacman -S archiso mkinitcpio-archiso git squashfs-tools grub --needed --noconfirm
          echo "ALL ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/nopasswd

      - name: Clone & Build
        run: |
          git clone https://github.com/cachyos/cachyos-live-iso.git cachyos-archiso
          cd cachyos-archiso
          ./buildiso.sh -p desktop -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: cachyos-archiso/out/**
